// Codemap renderer: turns a graph.json into a compact markdown orientation
// map meant to be read by Claude — deterministic, token-budgeted, no LLM.
// Over budget, detail caps step down and the smallest modules drop, with a
// trim note saying what was left out (never a silent truncation).

import path from 'node:path';

const estTokens = (s) => Math.ceil(s.length / 4);

const plural = (n, word) => `${n} ${word}${n === 1 ? '' : 's'}`;

const fmtTok = (n) => {
  if (n >= 1e6) return (n / 1e6).toFixed(1) + 'M';
  if (n >= 1e3) return Math.round(n / 1e3) + 'k';
  return String(n);
};

export function renderCodemap(graph, { tokenBudget = 2000 } = {}) {
  const m = graph.meta || {};
  const modules = graph.nodes
    .filter((n) => n.kind === 'folder' || n.kind === 'file')
    .sort((a, b) => (b.files || b.tokensRead || 0) - (a.files || a.tokensRead || 0));
  const internal = new Map(); // from -> [{to, weight}] sorted desc
  const external = new Map();
  const docEdges = [];
  for (const e of graph.edges) {
    if (e.kind === 'mentions' || e.kind === 'observed') {
      docEdges.push(e);
    } else {
      const bucket = e.to.startsWith('pkg:') ? external : internal;
      if (!bucket.has(e.from)) bucket.set(e.from, []);
      bucket.get(e.from).push(e);
    }
  }
  for (const list of internal.values()) list.sort((a, b) => b.weight - a.weight);
  for (const list of external.values()) list.sort((a, b) => b.weight - a.weight);
  const routes = new Map(); // doc id -> [{to, kind, weight, sessions}]
  for (const e of docEdges) {
    if (!routes.has(e.from)) routes.set(e.from, []);
    routes.get(e.from).push(e);
  }
  for (const list of routes.values()) {
    list.sort((a, b) => (a.kind === 'observed' ? -1 : 1) - (b.kind === 'observed' ? -1 : 1) ||
      b.weight - a.weight);
  }

  const attempt = ({ edgeCap, extCap, nodeCap, routeCap }) => {
    const kept = modules.slice(0, nodeCap);
    const keptIds = new Set(kept.map((n) => n.id));
    const L = [];
    L.push(`# Codebase map — ${path.basename(m.root || 'project')}`);
    L.push('');
    L.push(`> Import structure${m.usage ? ' + measured session usage' : ''}, ` +
      `generated by Tokenscope. Built ${m.builtAt ? m.builtAt.slice(0, 10) : '?'}` +
      (m.gitHead ? ` at git ${m.gitHead.slice(0, 8)}` : '') +
      `, ${m.filesScanned || '?'} source files. "a → b" means files in a import from b.`);
    L.push('');
    L.push('## Modules');
    for (const n of kept) {
      const deps = (internal.get(n.id) || []).filter((e) => keptIds.has(e.to)).slice(0, edgeCap);
      const parts = [`- **${n.id}**`];
      const facts = [];
      if (n.files) facts.push(plural(n.files, 'file'));
      if (n.tokensRead) facts.push(`~${fmtTok(n.tokensRead)} tok read`);
      if (facts.length > 0) parts.push(`(${facts.join(', ')})`);
      if (deps.length > 0) {
        parts.push('→ ' + deps.map((e) => `${e.to} (${e.weight})`).join(', '));
      }
      L.push(parts.join(' '));
    }
    if (extCap > 0) {
      const lines = [];
      for (const n of kept) {
        const pkgs = (external.get(n.id) || []).slice(0, extCap)
          .map((e) => e.to.slice(4));
        if (pkgs.length > 0) lines.push(`- ${n.id}: ${pkgs.join(', ')}`);
      }
      if (lines.length > 0) {
        L.push('', '## Key external packages', ...lines);
      }
    }
    if (routes.size > 0 && routeCap > 0) {
      const lines = [];
      for (const [docId, list] of routes) {
        const targets = list.filter((e) => keptIds.has(e.to)).slice(0, routeCap)
          .map((e) => e.kind === 'observed'
            ? `${e.to} (used together in ${plural(e.sessions ?? e.weight, 'session')})`
            : `${e.to} (mentioned)`);
        if (targets.length > 0) lines.push(`- ${docId} → ${targets.join(', ')}`);
      }
      if (lines.length > 0) {
        L.push('', '## Docs routing — read the doc when working in its area', ...lines);
      }
    }
    const droppedNodes = modules.length - kept.length;
    if (droppedNodes > 0) {
      L.push('', `_(trimmed to fit: ${droppedNodes} smaller modules omitted)_`);
    }
    L.push('');
    return L.join('\n');
  };

  const steps = [
    { edgeCap: 8, extCap: 5, nodeCap: Infinity, routeCap: 4 },
    { edgeCap: 5, extCap: 3, nodeCap: Infinity, routeCap: 3 },
    { edgeCap: 4, extCap: 2, nodeCap: 30, routeCap: 2 },
    { edgeCap: 3, extCap: 1, nodeCap: 20, routeCap: 2 },
    { edgeCap: 2, extCap: 0, nodeCap: 12, routeCap: 1 },
  ];
  let text = attempt(steps[0]);
  for (const p of steps.slice(1)) {
    if (estTokens(text) <= tokenBudget) break;
    text = attempt(p);
  }
  return { text, tokens: estTokens(text) };
}
